[development]
address = "localhost"
port = 8000
workers = 5
keep_alive = 5
log = "normal"
secret_key = "IduYEpagvDJc1qInjvWkTAI09Bfll52MaNXWIKWkglA="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 5
keep_alive = 5
log = "normal"
secret_key = "eoo48ICMDKTXeMuLFUWyAbfFyUxLRsrcTAkTYD7H0ZI="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 80
workers = 5
keep_alive = 5
log = "critical"
secret_key = "dC37X6atp58qLkqx7eBtDnhhfIW9x1JELbk2F6KQOzI="
limits = { forms = 32768 }